### ISSUE TITLE
باگ افزودن ساب لینک دستی

### ISSUE THREAD

**Issue by vafaaee** [hiddify/HiddifyAndroidNG#22]
عزیزان دل
یه باگ عجیبی یافتم
وقتی لینک ساب رو دستی طبق فرمتی که برای hiddify گذاشتید میسازم، یعنی این فرمت 👇
hiddify://install-sub?url=

یعنی این 👇
hiddify://install-sub?url=https://****/785da931-df06-4b74-a369-20affd100a3b/all.txt?name=Sub1-unknown&asn=unknown&mode=new

لیست کانکشن هایی که میاره اونهایی نیست که برای اون ساب دامین مشخص کردیم، کانفیگ های پیش فرض ساب دامین اون سابسکرایپشن رو میاره 👀 فرقی هم نمیکنه ساب معمولی باشه یا b64

**Comment by hiddify1** [comment]
چون url را از خود پنل نگرفتید از لینک خود پنل استفاده کنید

**Comment by vafaaee** [comment]
خب اگر قرار باشه صرفا از همون url پنل استفاده کنیم، دیگه این قالب
hiddify://install-sub?url
کاربردی نداره 🤦‍♂️در واقع خاستم طبق چیزی که توی کانال گفتید از این قالب برای قابلیت کلیک کردن لینک ساب استفاده کنیم، تستش کنم

**Comment by hiddify1** [comment]
اون فقط برای کلیک هست

توی پنل قسمت qtcode بزنید لینک اشتراک برای شبکه های اجتماعی
