### ISSUE TITLE
حذف لودبالانس و لوست پینگ

### ISSUE THREAD

**Issue by Vahiid-gh** [hiddify/HiddifyAndroidNG#24]
سلام
 یه لینک ساب دارم که وقتی رفرش میکنم چندتا کانفیگ برام میاره
بعد پینگ میگیرم و با گزینه delete invalid config اونایی که پینگ نمیاره رو پاک میکنم...
وقتی اینکارو میکنم لود بالانس و لوست پینگ هم باهاش حذف میشه و عملا دیگه از قسمت hiddify نمیتونم استفاده کنم

**Comment by hiddify1** [comment]
fixed
