### ISSUE TITLE
مشکلات نسخه 3

### ISSUE THREAD

**Issue by alirezasamavarchi** [hiddify/HiddifyAndroidNG#3]
سلام و خسته نباشید به تیم hiddify
مشکلاتی که بهش برخورد کردم و لازم بود عنوان بشه برای فیکس کردنش
1- لینک ساب رو توی برنامه import میکنی ثبت میشه ولی کانفیگ ها رو نمیاره و برنامه کرش میکنه
ولی میشه کانفیگ ها رو دستی وارد کرد و کار میده
2- برنامه وقتی استارت میخوره بعد از چند ثانیه خودکار قطع میشه و دیگه vpn خاموش میشه
3- تنظیمات برای دایرکت کردن و بلاک کردن ( routing ) نداشت. ( این مورد توی نسخه desk انجام شده بود )

**Comment by hiddify1** [comment]
1- لینکتون رو به hiddify@gmail.com بفرستید
2- کانفیگتون را میفرستید؟
بخش 3 نیاز به کار بیشتر داره تو آپدیت های بعدی میاریم

**Comment by cyb3rdom** [comment]
سلام و خسته نباشید به تیم هیدیفای
منم مشکلات بالا رو دارم مخصوصا شماره 2

**Comment by Sadeqss** [comment]
عرض سلام و خسته نباشید 
من نسخه جدید hiddifyNG رو نصب کردم. روی ویندوز با سرعت خوبی کار میکنه. روی اندروید روی ۲ تا گوشی که یکیش اندروید ۱۰ هست و یکیش ۱۲ بعد از حدود ۳۰ تا ۴۰ ثانیه ارتباط قطع میشه و باید دوباره وصل بشم و وین پروسه تکرار میشه. نسخه برنامه اندروید هم ۱.۲.۳ هست

**Comment by hiddify1** [comment]
کانفیگتون را میفرستید hiddify@gmail.com

**Comment by alirezasamavarchi** [comment]
آپدیت جدید خیلی خوب شده ولی مشکل قطع شدن vpn بعد از چند ثانیه هنوز هست

**Comment by hiddify1** [comment]
fixed in 1.4.0
